// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqwteyihookfakxzcxlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xd3RleWlob29rZmFreHpjeGx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MTYzMzUsImV4cCI6MjA1NDA5MjMzNX0.Ql3Nv7713pKubU9jAkPIkjYOe5EBKykEv01_W3HzjeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);